### ISSUE TITLE
Different version of Blauberg communication protocol 

### ISSUE THREAD

**Issue by Styx85** [ynsgnr/blauberg-assistant#1]
As far as I have seen it there are three slightly different protocols for communication with blauberg vents:
Beside smartir there is also the vento v2 (https://github.com/gody01/ecovent_v2) and the vento v1 (https://github.com/aglehmann/pyEcovent).
Would it be possible for you to integrate them all into one integration that automatically chooses the right protocol? I could test the v2 as I own here more than one vent.

**Comment by ynsgnr** [comment]
Thanks for the comment!

Can you share the documentation for V2, currently I have [this documentation](https://blaubergventilatoren.de/en/download/9563) from [here](https://blaubergventilatoren.de/en/series/smart-wifi-smart-ir-wifi#downloads) for the fan I own, not sure which version it uses but protocols seems very familar

Theoretically it should be possible to automatically detect versions and handle it

**Comment by ynsgnr** [comment]
As far as I seen there is no difference in version, adding new devices under https://github.com/ynsgnr/blauberg-assistant/tree/main/custom_components/blauberg_fan/blauberg_protocol/devices would make it compatible with possibly any blauberg fan.

I don't have any other fan than "Smart Wi-Fi". @Styx85 if you have a fan you can try experimenting by adding `parameter_map` for it, and you can do that in your PC as well no need for home assistant, just follow the [readme](https://github.com/ynsgnr/blauberg-assistant/tree/main/custom_components/blauberg_fan/blauberg_protocol)

**Comment by ynsgnr** [comment]
Closed due to no response
